"""Write brand/ark-figures.json from the two places that author its contents.

The colours are read from theme.css, which is where every Econ-ARK colour is authored, and the two
printed widths from ark/layout.typ through scripts/widths.typ, which is where the page geometry is.
A repository drawing figures reads this file, which is what keeps one copy of each value.

    uv run --no-project python scripts/brand-figures.py           # write brand/ark-figures.json
    uv run --no-project python scripts/brand-figures.py --stdout  # print it, which the suite diffs
"""

import json
import logging
import re
import subprocess
import sys
from pathlib import Path

log = logging.getLogger("brand-figures")

ROOT = Path(__file__).resolve().parent.parent
# Name in the file, token in theme.css. The names say what a figure uses the colour for, since a
# repository reading this file knows nothing of the stylesheet's own names.
COLOURS = {
    "ink": "ark-code-ink",
    "muted": "ark-grey",
    "rule": "ark-rule",
    "paper": "ark-paper",
    "tint": "ark-tint",
    "blue": "ark-blue",
    "datum": "ark-datum",
}
LINES = ["ark-line-1", "ark-line-2", "ark-line-3", "ark-line-4"]
CURVES = ["ark-curve-1", "ark-curve-2", "ark-curve-3", "ark-curve-4"]


def tokens() -> dict[str, str]:
    """Every --ark-* colour theme.css declares in a :root block, which is the light theme.

    Nine of the tokens are declared twice, once here and once under html.dark. Keeping the first
    of each across the whole file would take the light value only for as long as :root precedes
    html.dark in the source, so a stylesheet regrouped by theme would hand every figure the dark
    palette. Only the :root blocks are read, so the theme is chosen by scope. A token declared
    only under html.dark is then absent, and document() raises on it.
    """
    found: dict[str, str] = {}
    pattern = re.compile(r"--(ark-[a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8})\s*;")
    css = (ROOT / "theme.css").read_text(encoding="utf-8")
    for block in re.findall(r":root\s*\{([^}]*)\}", css):
        for name, value in pattern.findall(block):
            if name not in found:
                found[name] = expand(value.lower())
    return found


def expand(value: str) -> str:
    raw = value.lstrip("#")
    return "#" + ("".join(ch * 2 for ch in raw) if len(raw) == 3 else raw)


def widths() -> dict[str, float]:
    """The printed widths in inches, from the layout the template pages with."""
    out = subprocess.run(
        [
            "typst",
            "eval",
            "query(<ark-widths>).map(it => it.value)",
            "--in",
            "scripts/widths.typ",
            "--root",
            ".",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    points = json.loads(out.stdout)[0]
    # A renamed field would otherwise leave widths_in short a key, and the file is schema-valid
    # either way: the consumer reading it is what breaks, a repository away from this script.
    if set(points) != {"column", "wide"}:
        raise SystemExit(
            f"scripts/widths.typ gave {sorted(points)}, not ['column', 'wide']"
        )
    return {name: round(value / 72, 3) for name, value in points.items()}


def document() -> dict:
    declared = tokens()
    missing = [t for t in list(COLOURS.values()) + LINES + CURVES if t not in declared]
    if missing:
        raise SystemExit(f"theme.css declares no {', '.join(missing)}")
    return {
        "note": "Generated by scripts/brand-figures.py from theme.css and ark/layout.typ. Edit those.",
        "colors": {name: declared[token] for name, token in COLOURS.items()},
        "lines": [declared[token] for token in LINES],
        "curves": [declared[token] for token in CURVES],
        "widths_in": widths(),
    }


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stdout)
    text = json.dumps(document(), indent=2) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(text)
        return
    (ROOT / "brand" / "ark-figures.json").write_text(text, encoding="utf-8")
    log.info("wrote brand/ark-figures.json")


main()
